# fly.toml app configuration file generated for icy-sea-3390 on 2023-07-12T18:41:17+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "icy-sea-3390"
primary_region = "waw"
console_command = "/rails/bin/rails console"

[deploy]
  release_command = "./bin/rails db:prepare"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
